# Generated by Django 3.0.6 on 2020-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['-created_on'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=400),
        ),
    ]
