# Generated by Django 3.0.5 on 2020-07-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200709_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
    ]
