# Generated by Django 3.0.5 on 2020-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_delete_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
