# Generated by Django 3.0.5 on 2020-08-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_post_enable_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(editable=False, max_length=255)),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='articles.Post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
