# Generated by Django 3.0.5 on 2020-08-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_hit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
