# Generated by Django 3.0.5 on 2020-08-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200805_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
