# Generated by Django 3.0.5 on 2020-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20200808_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
    ]
