# Generated by Django 3.0.5 on 2020-08-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_post_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='carousel',
        ),
    ]
