# Generated by Django 3.0.5 on 2020-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_remove_post_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
    ]
