# Generated by Django 3.0.6 on 2020-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_plot_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='div',
        ),
        migrations.AddField(
            model_name='plot',
            name='figure',
            field=models.TextField(blank=True, default='Figure placeholder'),
        ),
    ]
