# Generated by Django 3.0.6 on 2020-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200703_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='on_focus',
            field=models.BooleanField(default=False),
        ),
    ]
