# Generated by Django 3.0.5 on 2020-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200712_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
