# Generated by Django 3.0.5 on 2020-07-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200712_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='city',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='country',
        ),
        migrations.AddField(
            model_name='vote',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
