# Generated by Django 3.0.5 on 2020-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200713_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-voted_on']},
        ),
        migrations.AlterField(
            model_name='plot',
            name='allow_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.IntegerField(choices=[(0, 'Linear'), (1, 'Histogram')], default=1),
        ),
    ]
