# Generated by Django 3.0.5 on 2020-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200713_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
