# Generated by Django 3.0.5 on 2020-07-13 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200713_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip2locationdbupdate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip2locationdbupdate',
            name='db_name',
            field=models.CharField(blank=True, default='DB3LITEBIN', max_length=10, verbose_name='Database code'),
        ),
        migrations.AlterField(
            model_name='ip2locationdbupdate',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
