# Generated by Django 3.0.5 on 2020-07-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200713_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip2locationdbupdate',
            old_name='db_name',
            new_name='db_code',
        ),
    ]
