# Generated by Django 3.0.5 on 2020-07-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200713_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP2LocationDBUpdate',
        ),
    ]
