# Generated by Django 3.0.5 on 2020-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_delete_ip2locationdbupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
    ]
