# Generated by Django 3.0.5 on 2020-08-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_plot_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='created_on',
        ),
    ]
