# Generated by Django 3.0.5 on 2020-08-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200811_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
